### ISSUE TITLE
Assertion Failure, "GET with special characters"

### ISSUE THREAD

**Issue by mrandrewmills** [akamai/AkamaiOPEN-edgegrid-java#35]
I don't work with Java often, so I may be doing something wrong and/or making an invalid assumption. If so, apologies in advance.

Here's what's happening:

1) I'm using Maven to build .jar files of the various .java files, using the "mvn package" command within the edgegrid-signer-core subfolder.

2) Maven runs 46 tests, fails 1, and then the build halts.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project edgegrid-signer-core: There are test failures.`

3) When I dig into /target/surefire-reports/, I see more details. I'm seeing what appear to be client and access tokens (not mine) in the report, so I'm a little reluctant to copy/paste directly into this issue for fear of exposing credentials. I can tell you the expected signature and the actual signatures are where the assertion falls apart, everything else is identical. If it's ok to post with the access and client token from the report, let me know and I'll add them if it's helpful.

I know it's possible to direct Maven build the package without running the tests, but when I've tried this I find what appear to be unhandled exceptions within the resulting EdgeGridV1Signer.class-- so I'm inferring the underlying issue of the test failing is something which needs to be addressed before I can leverage EdgeGridV1Signer.class successfully as a .jar file in my application.

Have I missed something silly & obvious (e.g. replacing access and client token values in a config file before building with Maven), or is the failing test indicating a legit problem within EdgeGridV1Signer.java which needs fixing?

**Comment by elreydetodo** [comment]
Looks like there is some sort of compatibility issue with Java > 8. I hadn't tried to compile with any newer version of Java to this point because we were aiming to maintain compatibility back as far as Java 8.

I don't know exactly what the problem is yet. Something about the signing algorithm is coming up with a different request signature with newer Java versions. Off the top of my head, I can't think of anything about the implementation that should care about the specific JVM being used.

**Comment by elreydetodo** [comment]
The issue was a test problem, but I discovered a related minor bug in the process of debugging. The test that starts failing with Java 11 is somehow mis-using the multi-arg constructor in URI. I don't really understand what the problem was with the usage or why it changed between Java 8 and Java 11, but I debugged into the thing and made sure that the thing being signed is exactly the thing we mean to be signed (the query string containing percent-encoded data in this case).

The bug found in the process of discovery is that we apparently need to use URI#getRawPath() to keep the percent-encoded path segments. That's really only a minor correctness issue, since no Akamai OPEN API should be using paths that contain unsafe/escapable URI characters in the path. Most of them won't even have any in the query string (the thing that caused the initial test failure).

Note that this project still does not compile with Java 11 even after the update I just made to the unit tests. It looks like there's a dependency on JAXB coming in through restassured, and all the javax.* modules left the JRE as part of Java 9, so the dependency is broken. There's a newer version of restassured that seems to have Java > 9 support, but when I upgraded that I found a problem with Gatling. After I upgraded that I found a problem with something else.

I don't have time to dig into all of this right now, but it's likely just a matter of bumping a few dependencies and making sure there are no more test failures due to classes and methods not found. I'd love to accept a PR for this. Either way though it'd be helpful to open a new issue with whatever build failures you encounter with Java 11 or Java 12 after this last patch was pushed.

**Comment by mrandrewmills** [comment]
Thank you for the quick response and looking into this. I'll download the latest patch and be sure I'm working with Java 8 to get things working, and then see what information I can gather re: Java 11 build failures. I wish I knew more Java so I could give you a PR which would address the remaining dependencies, but I'd be lying if I claimed I understood more than about 50% of your third paragraph ATM.
