### ISSUE TITLE
[DXE-3525] Dependency on vulnerable library

### ISSUE THREAD

**Issue by marcinm-c** [akamai/AkamaiOPEN-edgegrid-java#53]
Hi,

Project depends on httpclient version 4.5.13 which  has got some detected vulnerabilities (see https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.13) Would it be possible to update httpclient to safe version?

thx

**Comment by PawelSnoch** [comment]
Hi @marcinm-c ,

Thank you for reporting this ticket. We will update httpclient when new version without vulnerabilities is available.
The latest one 4.5.14 has the same issue https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.14

Best regards,
Pawel

**Comment by marcinm-c** [comment]
The newest version of https://mvnrepository.com/artifact/org.apache.httpcomponents.client5/httpclient5/5.3.1 is free of vulnerabilities (at least for now) but probably that's bigger change - don't know if its backward compatible

**Comment by PawelSnoch** [comment]
Hi @marcinm-c ,

We created ticket to investigate potential risk of this update. We will get back to you.

Thanks,
Pawel

**Comment by mgwoj** [comment]
Hello @marcinm-c ,

As you could notice migration to client 5 is a bigger change as versions 4 and 5 are not fully compatible, last year we have added [edgegrid-signer-apache-http-client5](https://github.com/akamai/AkamaiOPEN-edgegrid-java/tree/master/edgegrid-signer-apache-http-client5) which is based on client 5. Please consider using it instead of [edgegrid-signer-apache-http-client](https://github.com/akamai/AkamaiOPEN-edgegrid-java/tree/master/edgegrid-signer-apache-http-client).
Please let us know if this is acceptable solution for you.

Thanks,
Michal

**Comment by marcinm-c** [comment]
Thank you. That's what we need. 

Cheers,
Marcin
